<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Asistencia extends CI_Controller{
  function __construct()
  {
    parent::__construct();
    $this->load->model('Asistencia_model');
    $this->load->model('Curso_model');
  }

  function control($id_curso){
    $data['curso'] = $this->Curso_model->get_curso($id_curso);

    if(isset($data['curso']['id'])){
      $data['title'] = 'Asistencia - ESMN';
      $data['page_title'] = 'Asistencia';

      $data['asistencia'] = $this->Asistencia_model->get_asistencia($id_curso);
      $data['diascursado'] = json_decode($data['asistencia'][0]['diascursado']);

      $data['css'] = array('curso.css');
      $data['js'] = array('asistencia.js');

      $this->load->view('templates/header',$data);
      $this->load->view('asistencia/control',$data);
      $this->load->view('templates/footer');

    }
    else
    show_error('The asistencia you are trying to load does not exist.');
  }

  /*
  * Listing of asistenciacias
  */
  // function index()
  // {
  //     $data['asistenciacias'] = $this->Asistencia_model->get_all_asistenciacias();
  //
  //     $data['_view'] = 'asistencia/index';
  //     $this->load->view('layouts/main',$data);
  // }
  //
  // /*
  //  * Adding a new asistencia
  //  */
  // function add()
  // {
  //     $this->load->library('form_validation');
  //
  // $this->form_validation->set_rules('id_estado','Id Estado','required|integer');
  //
  // if($this->form_validation->run())
  //     {
  //         $params = array(
  // 		'id_estado' => $this->input->post('id_estado'),
  //         );
  //
  //         $asistencia_id = $this->Asistencia_model->add_asistencia($params);
  //         redirect('asistencia/index');
  //     }
  //     else
  //     {
  // 	$this->load->model('Estado_asistencia_model');
  // 	$data['all_estado_asistencia'] = $this->Estado_asistencia_model->get_all_estado_asistencia();
  //
  //         $data['_view'] = 'asistencia/add';
  //         $this->load->view('layouts/main',$data);
  //     }
  // }
  //
  // /*
  //  * Editing a asistencia
  //  */
  // function edit($id_asiste)
  // {
  //     // check if the asistencia exists before trying to edit it
  //     $data['asistencia'] = $this->Asistencia_model->get_asistencia($id_asiste);
  //
  //     if(isset($data['asistencia']['id_asiste']))
  //     {
  //         $this->load->library('form_validation');
  //
  // 	$this->form_validation->set_rules('id_estado','Id Estado','required|integer');
  //
  // 	if($this->form_validation->run())
  //         {
  //             $params = array(
  // 			'id_estado' => $this->input->post('id_estado'),
  //             );
  //
  //             $this->Asistencia_model->update_asistencia($id_asiste,$params);
  //             redirect('asistencia/index');
  //         }
  //         else
  //         {
  // 		$this->load->model('Estado_asistencia_model');
  // 		$data['all_estado_asistencia'] = $this->Estado_asistencia_model->get_all_estado_asistencia();
  //
  //             $data['_view'] = 'asistencia/edit';
  //             $this->load->view('layouts/main',$data);
  //         }
  //     }
  //     else
  //         show_error('The asistencia you are trying to edit does not exist.');
  // }
  //
  // /*
  //  * Deleting asistencia
  //  */
  // function remove($id_asiste)
  // {
  //     $asistencia = $this->Asistencia_model->get_asistencia($id_asiste);
  //
  //     // check if the asistencia exists before trying to delete it
  //     if(isset($asistencia['id_asiste']))
  //     {
  //         $this->Asistencia_model->delete_asistencia($id_asiste);
  //         redirect('asistencia/index');
  //     }
  //     else
  //         show_error('The asistencia you are trying to delete does not exist.');
  // }

}
