<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Ciudad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get ciudad by id
     */
    function get_ciudad($id)
    {
        return $this->db->get_where('ciudad',array('id'=>$id))->row_array();
    }

    /*
     * Get all ciudades count
     */
    function get_all_ciudades_count()
    {
        $this->db->from('ciudad');
        return $this->db->count_all_results();
    }

    /*
     * Get all ciudades
     */
    function get_all_ciudades($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('ciudad')->result_array();
    }

    /*
     * function to add new ciudad
     */
    function add_ciudad($params)
    {
        $this->db->insert('ciudad',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update ciudad
     */
    function update_ciudad($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('ciudad',$params);
    }

    /*
     * function to delete ciudad
     */
    function delete_ciudad($id)
    {
        return $this->db->delete('ciudad',array('id'=>$id));
    }
}
