<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Curso extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        validar_acceso();
        is_logged_in();
        $this->load->model('Curso_model');
        $this->load->model('Materia_model');
        $this->load->model('Periodo_model');
        $this->load->model('Carrera_model');
        $this->load->model('Modelo_global_model');

    }

    /*
     * Listing of curso
     */
    function index()
    {
        $data['cursos'] = $this->Curso_model->get_all_curso();

        $data['title'] = 'Cursos - ESMN';
        $data['page_title'] = 'Curso';

        //validar botones
        $data['boton_edit']=validar_botones('edit');
        $data['boton_add']=validar_botones('add');
        $data['boton_remove']=validar_botones('remove');

        // script de correlatividades
        //$data['js'] = array('curso_index.js');

        $this->load->view('templates/header',$data);
        $this->load->view('curso/index',$data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new curso
     */
    function add()
    {
        $this->form_validation->set_rules('id_materia','Materia','required|integer');
        $this->form_validation->set_rules('id_periodo','Periodo','required|integer');
        $this->form_validation->set_rules('dayweek[]','Dayweek','required');

        if($this->form_validation->run())
        {
            $dias_cursado=$this->input->post('dayweek[]');
            $datos_periodo=$this->Periodo_model->get_Periodo($this->input->post('id_periodo'));
            $desde=$datos_periodo['desde'];
            $hasta=$datos_periodo['hasta'];
            $where='';
            foreach ($dias_cursado as $dia)
            {
                $where.=' or dayofweek(DIASENTREFECHAS) = '.$dia;
                
            }
            $where= substr($where, 4);
            
            $dias_cursado_string=json_encode($this->Modelo_global_model->fechas_de_intervalos($desde, $hasta, $where));
            
            $params = array(
                'id' => $this->input->post('id'),
                'id_materia' => $this->input->post('id_materia'),
                'id_periodo' =>$this->input->post('id_periodo'),
                'diascursado' => $dias_cursado_string,

            );

            $curso_id = $this->Curso_model->add_curso($params);
            $this->session->set_flashdata('crear', 'Nuevo curso creado');
            redirect('curso/index');
        }

        else
        {
            $data['title'] = 'curso - ESMN';
            $data['page_title'] = 'Nueva curso';

            $data['all_materias'] = $this->Materia_model->get_all_materias();
            $data['all_periodos'] = $this->Periodo_model->get_all_periodo();

            $this->load->view('templates/header',$data);
            $this->load->view('curso/add',$data);
            $this->load->view('templates/footer');
        }
    }

    /*
     * Editing a curso
     */
    function edit($id)
    {
        // check if the curso exists before trying to edit it
        $data['curso'] = $this->Curso_model->get_curso($id);

        if(isset($data['curso']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'id_curso' => $this->input->post('id_curso'),
					'periodo' => $this->input->post('periodo'),
					'diascursado' => $this->input->post('diascursado'),
                );

                $this->Curso_model->update_curso($id,$params);
                redirect('curso/index');
            }
            else
            {
                $data['_view'] = 'curso/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The curso you are trying to edit does not exist.');
    }

    /*
     * Deleting curso
     */
    function remove($id)
    {
        $curso = $this->Curso_model->get_curso($id);

        // check if the curso exists before trying to delete it
        if(isset($curso['id']))
        {
            $this->Curso_model->delete_curso($id);
            redirect('curso/index');
        }
        else
            show_error('The curso you are trying to delete does not exist.');
    }

}
