<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Estado_cursado extends CI_Controller{
  function __construct()
  {
    parent::__construct();
    is_logged_in();
    validar_acceso();
    $this->load->model('estado_cursado_model');
  }

  /*
  * Listing of estado_cursado
  */
  function index()
  {
    $params['limit'] = RECORDS_PER_PAGE;
    $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

    $config = $this->config->item('pagination');
    $config['base_url'] = site_url('estado_cursado/index?');
    $config['total_rows'] = $this->estado_cursado_model->get_all_estado_cursado_count();
    $this->pagination->initialize($config);

    $data['estado_cursado'] = $this->estado_cursado_model->get_all_estado_cursado($params);

    $data['page_title'] = 'Estados de cursado - ESMN';
    $data['title'] = 'Estados de cursado';

    //Botones de acciones
    $data['boton_edit']=validar_botones('edit');
    $data['boton_add']=validar_botones('add');
    $data['boton_remove']=validar_botones('remove');

    $this->load->view('templates/header',$data);
    $this->load->view('estado_cursado/index',$data);
    $this->load->view('templates/footer');
  }

  /*
  * Adding a new estado_cursado
  */
  function add()
  {
    $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');
    $this->form_validation->set_rules('nomenclatura','Nomenclatura','max_length[4]');

    if($this->form_validation->run())
    {
      $params = array(
        'nombre' => $this->input->post('nombre'),
        'nomenclatura' => $this->input->post('nomenclatura'),
      );

      $estado_cursado_id = $this->estado_cursado_model->add_estado_cursado($params);
      redirect('estado_cursado/index');
    }
    else
    {
      $data['page_title'] = 'Nuevo estado de cursado - ESMN';
      $data['title'] = 'Nuevo estado de cursado';

      $this->load->view('templates/header',$data);
      $this->load->view('estado_cursado/add',$data);
      $this->load->view('templates/footer');
    }
  }

  /*
  * Editing a estado_cursado
  */
  function edit($id)
  {
    // check if the estado_cursado exists before trying to edit it
    $data['estado_cursado'] = $this->estado_cursado_model->get_estado_cursado($id);

    if(isset($data['estado_cursado']['id']))
    {
      $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');
      $this->form_validation->set_rules('nomenclatura','Nomenclatura','max_length[4]');

      if($this->form_validation->run())
      {
        $params = array(
          'nombre' => $this->input->post('nombre'),
          'nomenclatura' => $this->input->post('nomenclatura'),
        );

        $this->estado_cursado_model->update_estado_cursado($id,$params);
        redirect('estado_cursado/index');
      }
      else
      {
        $data['page_title'] = 'Editar estado de cursado - ESMN';
        $data['title'] = 'Editar estado de cursado';

        $this->load->view('templates/header',$data);
        $this->load->view('estado_cursado/edit',$data);
        $this->load->view('templates/footer');
      }
    }
    else
    show_error('The estado_cursado you are trying to edit does not exist.');
  }

  /*
  * Deleting estado_cursado
  */
  function remove($id)
  {
    $estado_cursado = $this->estado_cursado_model->get_estado_cursado($id);

    // check if the estado_cursado exists before trying to delete it
    if(isset($estado_cursado['id']))
    {
      $this->estado_cursado_model->delete_estado_cursado($id);
      redirect('estado_cursado/index');
    }
    else
    show_error('The estado_cursado you are trying to delete does not exist.');
  }

}
