<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Estado_asistencia extends CI_Controller{
  function __construct()
  {
    parent::__construct();
    validar_acceso();
    is_logged_in();
    $this->load->model('Estado_asistencia_model');
  }

  /*
  * Listing of estado_asistencia
  */
  function index()
  {
    $params['limit'] = RECORDS_PER_PAGE;
    $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

    $config = $this->config->item('pagination');
    $config['base_url'] = site_url('estado_asistencia/index?');
    $config['total_rows'] = $this->Estado_asistencia_model->get_all_estado_asistencia_count();
    $this->pagination->initialize($config);

    $data['estado_asistencia'] = $this->Estado_asistencia_model->get_all_estado_asistencia($params);

    $data['page_title'] = 'Estados de asistencia - ESMN';
    $data['title'] = 'Estados de asistencia';

    //Botones de acciones
    $data['boton_edit']=validar_botones('edit');
    $data['boton_add']=validar_botones('add');
    $data['boton_remove']=validar_botones('remove');

    $this->load->view('templates/header',$data);
    $this->load->view('estado_asistencia/index',$data);
    $this->load->view('templates/footer');
  }

  /*
  * Adding a new estado_asistencia
  */
  function add()
  {
    $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');
    $this->form_validation->set_rules('nomenclatura','Nomenclatura','max_length[4]');

    if($this->form_validation->run())
    {
      $params = array(
        'nombre' => $this->input->post('nombre'),
        'nomenclatura' => $this->input->post('nomenclatura'),
      );

      $estado_asistencia_id = $this->Estado_asistencia_model->add_estado_asistencia($params);
      redirect('estado_asistencia/index');
    }
    else
    {
      $data['page_title'] = 'Nuevo estado de asistencia - ESMN';
      $data['title'] = 'Nuevo estado de asistencia';

      $this->load->view('templates/header',$data);
      $this->load->view('estado_asistencia/add',$data);
      $this->load->view('templates/footer');
    }
  }

  /*
  * Editing a estado_asistencia
  */
  function edit($id)
  {
    // check if the estado_asistencia exists before trying to edit it
    $data['estado_asistencia'] = $this->Estado_asistencia_model->get_estado_asistencia($id);

    if(isset($data['estado_asistencia']['id']))
    {
      $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');
      $this->form_validation->set_rules('nomenclatura','Nomenclatura','max_length[4]');

      if($this->form_validation->run())
      {
        $params = array(
          'nombre' => $this->input->post('nombre'),
          'nomenclatura' => $this->input->post('nomenclatura'),
        );

        $this->Estado_asistencia_model->update_estado_asistencia($id,$params);
        redirect('estado_asistencia/index');
      }
      else
      {
        $data['page_title'] = 'Editar estado de asistencia - ESMN';
        $data['title'] = 'Editar estado de asistencia';

        $this->load->view('templates/header',$data);
        $this->load->view('estado_asistencia/edit',$data);
        $this->load->view('templates/footer');
      }
    }
    else
    show_error('The estado_asistencia you are trying to edit does not exist.');
  }

  /*
  * Deleting estado_asistencia
  */
  function remove($id)
  {
    $estado_asistencia = $this->Estado_asistencia_model->get_estado_asistencia($id);

    // check if the estado_asistencia exists before trying to delete it
    if(isset($estado_asistencia['id']))
    {
      $this->Estado_asistencia_model->delete_estado_asistencia($id);
      redirect('estado_asistencia/index');
    }
    else
    show_error('The estado_asistencia you are trying to delete does not exist.');
  }

}
