<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class estado_inscripcion_final extends CI_Controller{
  function __construct()
  {
    parent::__construct();
    is_logged_in();
    validar_acceso();
    $this->load->model('estado_inscripcion_final_model');
  }

  /*
  * Listing of estado_inscripcion_final
  */
  function index()
  {
    $data['estado_inscripcion_final'] = $this->estado_inscripcion_final_model->get_all_estado_inscripcion_final();

    $data['title'] = 'Estados de inscripcion final - ESMN';
    $data['page_title'] = 'Estados de inscripcion final';

    //Botones de acciones
    $data['boton_edit']=validar_botones('edit');
    $data['boton_add']=validar_botones('add');
    $data['boton_remove']=validar_botones('remove');

    $this->load->view('templates/header',$data);
    $this->load->view('estado_inscripcion_final/index',$data);
    $this->load->view('templates/footer');
  }

  /*
  * Adding a new estado_inscripcion_final
  */
  function add()
  {
    $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');
    $this->form_validation->set_rules('nomenclatura','Nomenclatura','max_length[4]');
    $this->form_validation->set_rules('radio-stacked','Tipo inscripcion','required');
    //     $this->form_validation->set_rules('customControlValidation2','Es cursado');

    if($this->form_validation->run())
    {
      if($this->input->post('radio-stacked') == 'mesa')
      {
        $mesa=1;
        $cursado=0;
      }
      else {
        $mesa=0;
        $cursado=1;
      }
      $params = array(
        'nombre' => $this->input->post('nombre'),
        'nomenclatura' => $this->input->post('nomenclatura'),
        'es_mesa' => $mesa,
        'es_cursado' => $cursado
      );

      $estado_inscripcion_final_id = $this->estado_inscripcion_final_model->add_estado_inscripcion_final($params);
      redirect('estado_inscripcion_final/index');
    }
    else
    {
      $data['title'] = 'Nuevo estado - ESMN';
      $data['page_title'] = 'Nuevo estado de inscripcion final';

      $this->load->view('templates/header',$data);
      $this->load->view('estado_inscripcion_final/add',$data);
      $this->load->view('templates/footer');
    }
  }

  /*
  * Editing a estado_inscripcion_final
  */
  function edit($id)
  {
    // check if the estado_inscripcion_final exists before trying to edit it
    $data['estado_inscripcion_final'] = $this->estado_inscripcion_final_model->get_estado_inscripcion_final($id);

    if(isset($data['estado_inscripcion_final']['id']))
    {
      $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');
      $this->form_validation->set_rules('nomenclatura','Nomenclatura','max_length[4]');
      $this->form_validation->set_rules('radio-stacked','Tipo inscripcion','required');

      if($this->form_validation->run())
      {
        if($this->input->post('radio-stacked') == 'mesa')
        {
          $mesa=1;
          $cursado=0;
        }
        else {
          $mesa=0;
          $cursado=1;
        }
        $params = array(
          'nombre' => $this->input->post('nombre'),
          'nomenclatura' => $this->input->post('nomenclatura'),
          'es_mesa' => $mesa,
          'es_cursado' => $cursado
        );

        $this->estado_inscripcion_final_model->update_estado_inscripcion_final($id,$params);
        redirect('estado_inscripcion_final/index');
      }
      else
      {
        $data['title'] = 'Editar estado - ESMN';
        $data['page_title'] = 'Editar estado de inscripcion final';

        $this->load->view('templates/header',$data);
        $this->load->view('estado_inscripcion_final/edit',$data);
        $this->load->view('templates/footer');
      }
    }
    else
    show_error('The estado_inscripcion_final you are trying to edit does not exist.');
  }

  /*
  * Deleting estado_inscripcion_final
  */
  function remove($id)
  {
    $estado_inscripcion_final = $this->estado_inscripcion_final_model->get_estado_inscripcion_final($id);

    // check if the estado_inscripcion_final exists before trying to delete it
    if(isset($estado_inscripcion_final['id']))
    {
      $this->estado_inscripcion_final_model->delete_estado_inscripcion_final($id);
      redirect('estado_inscripcion_final/index');
    }
    else
    show_error('The estado_inscripcion_final you are trying to delete does not exist.');
  }

}
