<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Materia_correlativa extends CI_Controller{
  function __construct()
  {
    parent::__construct();
    is_logged_in();
    validar_acceso();
    $this->load->model('Materia_correlativa_model');
  }

  function ver_correlativas(){
    if ($this->input->is_ajax_request() && !empty($_POST)) {
      $materias = $this->Materia_correlativa_model->get_materia_correlativa($_POST['id_materia']);
      echo json_encode($materias);
    }
    return false;
  }

  /*
  * Adding a new materia_correlativa
  */
  function add()
  {
    if (!empty($_POST)) {
      $params=array(
        'id_materia'=>$_POST['id_materia'],
        'id_correlativa'=>$_POST['id_correlativa'],
      );
      $this->Materia_correlativa_model->add_materia_correlativa($params);
      redirect('materia/index');
    }
  }


  /*
  * Deleting materia_correlativa
  */
  function remove()
  {
    if ($this->input->is_ajax_request() && !empty($_POST)) {
      $this->Materia_correlativa_model->delete_materia_correlativa($_POST['id_materia'],$_POST['id_correlativa']);
    }
  }

}
