<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Materia_correlativa extends CI_Controller{
  function __construct()
  {
    parent::__construct();
    validar_acceso();
    is_logged_in();
    $this->load->model('Materia_correlativa_model');
  }

  /*
  * Listing of materias_correlativas
  */
  function index()
  {
    $params['limit'] = RECORDS_PER_PAGE;
    $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

    $config = $this->config->item('pagination');
    $config['base_url'] = site_url('materia_correlativa/index?');
    $config['total_rows'] = $this->Materia_correlativa_model->get_all_materias_correlativas_count();
    $this->pagination->initialize($config);

    $data['materias_correlativas'] = $this->Materia_correlativa_model->get_all_materias_correlativas($params);

    // $data['_view'] = 'materia_correlativa/index';
    // $this->load->view('layouts/main',$data);
    $data['title'] = 'Materias Correlativas - ESMN';
    $data['page_title'] = 'Materias Correlativas';
    $this->load->view('templates/header',$data);
    $this->load->view('materia_correlativa/index',$data);
    $this->load->view('templates/footer');
  }

  function ver_correlativas(){
    if ($this->input->is_ajax_request() && !empty($_POST)) {
      $materias = $this->Materia_correlativa_model->get_materia_correlativa($_POST['id_materia']);
      echo json_encode($materias);
    }
    return false;
  }

  /*
  * Adding a new materia_correlativa
  */
  function add()
  {
    if (!empty($_POST)) {
      $params=array(
        'id_materia'=>$_POST['id_materia'],
        'id_correlativa'=>$_POST['id_correlativa'],
      );
      $this->Materia_correlativa_model->add_materia_correlativa($params);
      redirect('materia/index');
    }
  }

  /*
  * Editing a materia_correlativa
  */
  // function edit($id_materia)
  // {
  //   // check if the materia_correlativa exists before trying to edit it
  //   $data['materia_correlativa'] = $this->Materia_correlativa_model->get_materia_correlativa($id_materia);
  //
  //   if(isset($data['materia_correlativa']['id_materia']))
  //   {
  //     if(isset($_POST) && count($_POST) > 0)
  //     {
  //       $params = array(
  //       );
  //
  //       $this->Materia_correlativa_model->update_materia_correlativa($id_materia,$params);
  //       redirect('materia_correlativa/index');
  //     }
  //     else
  //     {
  //       // $data['_view'] = 'materia_correlativa/edit';
  //       // $this->load->view('layouts/main',$data);
  //       $data['title'] = 'Materias Correlativas - ESMN';
  //       $data['page_title'] = 'Materias Correlativas';
  //       $this->load->view('templates/header',$data);
  //       $this->load->view('materia_correlativa/edit',$data);
  //       $this->load->view('templates/footer');
  //     }
  //   }
  //   else
  //   show_error('The materia_correlativa you are trying to edit does not exist.');
  // }

  /*
  * Deleting materia_correlativa
  */
  function remove()
  {
    if ($this->input->is_ajax_request() && !empty($_POST)) {
      $this->Materia_correlativa_model->delete_materia_correlativa($_POST['id_materia'],$_POST['id_correlativa']);
    }
  }

}
