<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Materia extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Materia_model');
    }

    /*
     * Listing of materias
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('materia/index?');
        $config['total_rows'] = $this->Materia_model->get_all_materias_count();
        $this->pagination->initialize($config);

        $data['materias'] = $this->Materia_model->get_all_materias($params);

        // $data['_view'] = 'materia/index';
        // $this->load->view('layouts/main',$data);
        $data['title'] = 'Materias - ESMN';
        $data['page_title'] = 'Materia';

          $this->load->view('templates/header',$data);
          $this->load->view('materia/index',$data);
          $this->load->view('templates/footer');
    }

    /*
     * Adding a new materia
     */
    function add()
    {

		$this->form_validation->set_rules('id_carrera','Id Carrera','required|max_length[11]');
		$this->form_validation->set_rules('nombre','Nombre','required|max_length[128]');
		$this->form_validation->set_rules('codigo_anio','Codigo Anio','max_length[24]');
		$this->form_validation->set_rules('regimen_cursado','Regimen Cursado','max_length[24]');
		$this->form_validation->set_rules('regimen_aprobacion','Regimen Aprobacion','max_length[24]');
		$this->form_validation->set_rules('carga_horaria','Carga Horaria','integer');
		$this->form_validation->set_rules('tipo_catedra','Tipo Catedra','max_length[24]');

		if($this->form_validation->run())
        {
        $params = array(
				'id_carrera' => $this->input->post('id_carrera'),
				'nombre' => $this->input->post('nombre'),
				'codigo_anio' => $this->input->post('codigo_anio'),
				'regimen_cursado' => $this->input->post('regimen_cursado'),
				'regimen_aprobacion' => $this->input->post('regimen_aprobacion'),
				'carga_horaria' => $this->input->post('carga_horaria'),
				'tipo_catedra' => $this->input->post('tipo_catedra'),
            );

            $materia_id = $this->Materia_model->add_materia($params);
            redirect('materia/index');
        }
        else
        {
            $data['title'] = 'Materia - ESMN';
            $data['page_title'] = 'Materia';

              $this->load->view('templates/header',$data);
              $this->load->view('materia/add',$data);
              $this->load->view('templates/footer');
        }
    }

    /*
     * Editing a materia
     */
    function edit($id)
    {
        // check if the materia exists before trying to edit it
        $data['materia'] = $this->Materia_model->get_materia($id);

        if(isset($data['materia']['id']))
        {

			$this->form_validation->set_rules('id_carrera','Id Carrera','required|max_length[11]');
			$this->form_validation->set_rules('nombre','Nombre','required|max_length[128]');
			$this->form_validation->set_rules('codigo_anio','Codigo Anio','max_length[24]');
			$this->form_validation->set_rules('regimen_cursado','Regimen Cursado','max_length[24]');
			$this->form_validation->set_rules('regimen_aprobacion','Regimen Aprobacion','max_length[24]');
			$this->form_validation->set_rules('carga_horaria','Carga Horaria','integer');
			$this->form_validation->set_rules('tipo_catedra','Tipo Catedra','max_length[24]');

			if($this->form_validation->run())
            {
                $params = array(
					'id_carrera' => $this->input->post('id_carrera'),
					'nombre' => $this->input->post('nombre'),
					'codigo_anio' => $this->input->post('codigo_anio'),
					'regimen_cursado' => $this->input->post('regimen_cursado'),
					'regimen_aprobacion' => $this->input->post('regimen_aprobacion'),
					'carga_horaria' => $this->input->post('carga_horaria'),
					'tipo_catedra' => $this->input->post('tipo_catedra'),
                );

                $this->Materia_model->update_materia($id,$params);
                redirect('materia/index');
            }
            else
            {
                $data['title'] = 'Materia - ESMN';
                $data['page_title'] = 'Materia';

                  $this->load->view('templates/header',$data);
                  $this->load->view('materia/edit',$data);
                  $this->load->view('templates/footer');
            }
        }
        else
            show_error('The materia you are trying to edit does not exist.');
    }

    /*
     * Deleting materia
     */
    function remove($id)
    {
        $materia = $this->Materia_model->get_materia($id);

        // check if the materia exists before trying to delete it
        if(isset($materia['id']))
        {
            $this->Materia_model->delete_materia($id);
            redirect('materia/index');
        }
        else
            show_error('The materia you are trying to delete does not exist.');
    }

}
