<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Materia extends CI_Controller{
  // funcion contructor de controlador clase materia
  function __construct()
  {
    parent::__construct();
    is_logged_in();
    validar_acceso();
    $this->load->model('Materia_model');
    $this->load->model('Carrera_model');
  }

  /*
  * listado de materias
  */
  function index()
  {
    $data['materias'] = $this->Materia_model->get_all_materias();

    $data['title'] = 'Materias - ESMN';
    $data['page_title'] = 'Materia';

    //validar botones
    $data['boton_edit']=validar_botones('edit');
    $data['boton_add']=validar_botones('add');
    $data['boton_remove']=validar_botones('remove');

    // script de correlatividades
    $data['js'] = array('materia_index.js');

    $this->load->view('templates/header',$data);
    $this->load->view('materia/index',$data);
    $this->load->view('templates/footer');
  }

  /*
  * funcion que permite agregar una nueva materia
  */
  function add()
  {
    // if ($this->input->post('id_carrera') && $this->input->post('nombre')) {
    $query = $this->Materia_model->get_materia_by_nombre($this->input->post('id_carrera'),$this->input->post('nombre'));
    $is_unique = (empty($query)) ? '' :'|is_unique[materia.nombre]';

    $this->form_validation->set_rules('id_carrera','Codigo de Plan','required|max_length[11]');
    $this->form_validation->set_rules('nombre','Nombre','required|max_length[128]'.$is_unique);
    $this->form_validation->set_rules('codigo_anio','Codigo Anio','max_length[24]');
    $this->form_validation->set_rules('regimen_cursado','Regimen Cursado','max_length[24]');
    $this->form_validation->set_rules('regimen_aprobacion','Regimen Aprobacion','max_length[24]');
    $this->form_validation->set_rules('carga_horaria','Carga Horaria','integer');
    $this->form_validation->set_rules('tipo_catedra','Tipo Catedra','required|max_length[24]');

    if($this->form_validation->run())
    {
      $params = array(
        'id_carrera' => $this->input->post('id_carrera'),
        'nombre' => $this->input->post('nombre'),
        'codigo_anio' => $this->input->post('codigo_anio'),
        'regimen_cursado' => $this->input->post('regimen_cursado'),
        'regimen_aprobacion' => $this->input->post('regimen_aprobacion'),
        'carga_horaria' => $this->input->post('carga_horaria'),
        'tipo_catedra' => $this->input->post('tipo_catedra'),
      );

      $materia_id = $this->Materia_model->add_materia($params);
      $this->session->set_flashdata('crear', 'Nueva materia creada');
      redirect('materia/index');
    }
    else
    {
      $data['title'] = 'Materia - ESMN';
      $data['page_title'] = 'Nueva Materia';
      $data['all_carreras'] = $this->Carrera_model->get_all_carreras(array(),array('row'=>'carrera.activo','value'=>1));

      $this->load->view('templates/header',$data);
      $this->load->view('materia/add',$data);
      $this->load->view('templates/footer');
    }
  }

  /*
  * funcion que permite editar una Materia
  */
  function edit($id)
  {
    //Comprueba si existe la materia antes de intentar editarla.
    $data['materia'] = $this->Materia_model->get_materia($id);

    if(isset($data['materia']['id']))
    {

      $this->form_validation->set_rules('id_carrera','Codigo de Plan','required|max_length[11]');
      $this->form_validation->set_rules('nombre','Nombre','required|max_length[128]');
      $this->form_validation->set_rules('codigo_anio','Codigo Anio','max_length[24]');
      $this->form_validation->set_rules('regimen_cursado','Regimen Cursado','max_length[24]');
      $this->form_validation->set_rules('regimen_aprobacion','Regimen Aprobacion','max_length[24]');
      $this->form_validation->set_rules('carga_horaria','Carga Horaria','integer');
      $this->form_validation->set_rules('tipo_catedra','Tipo Catedra','required|max_length[24]');

      if($this->form_validation->run())
      {
        $params = array(
          'id_carrera' => $this->input->post('id_carrera'),
          'nombre' => $this->input->post('nombre'),
          'codigo_anio' => $this->input->post('codigo_anio'),
          'regimen_cursado' => $this->input->post('regimen_cursado'),
          'regimen_aprobacion' => $this->input->post('regimen_aprobacion'),
          'carga_horaria' => $this->input->post('carga_horaria'),
          'tipo_catedra' => $this->input->post('tipo_catedra'),
        );

        $this->Materia_model->update_materia($id,$params);
        $this->session->set_flashdata('editar', 'Se guardaron los cambios');
        redirect('materia/index');
      }
      else
      {
        $data['title'] = 'Materia - ESMN';
        $data['page_title'] = 'Materia -> '.$data['materia']['nombre'];

        $data['all_carreras'] = $this->Carrera_model->get_all_carreras(array(),array('row'=>'carrera.activo','value'=>1));

        $this->load->view('templates/header',$data);
        $this->load->view('materia/edit',$data);
        $this->load->view('templates/footer');
      }
    }
    else
    show_error('La materia que intenta editar, no existe.');
  }

  /*
  * Funcion que permite eliminar una materia
  */
  function remove($id)
  {
    $materia = $this->Materia_model->get_materia($id);

    // Comprueba si la materia existe antes de intentar borrarla.
    if(isset($materia['id']))
    {
      $this->load->model('Curso_model');
      $this->load->model('Inscripcion_materia_model');
      $this->load->model('Mesa_model');
      $this->load->model('Materia_correlativa_model');

      $cursos = $this->Curso_model->get_all_curso(array('row'=>'id_materia','value'=>$id));
      $inscripciones = $this->Inscripcion_materia_model->get_all_inscripcion_materia(array('row'=>'id_materia','value'=>$id));
      $mesas = $this->Mesa_model->get_all_mesas(array('row'=>'id_materia','value'=>$id));
      $correlativas = $this->Materia_correlativa_model->get_all_materias_correlativas(array(),array('row'=>'id_materia','value'=>$id));

      if (empty($cursos) && empty($inscripciones) && empty($mesas) && empty($correlativas)) {
        $this->Materia_model->update_materia($id,array('activo'=>0));
        $this->session->set_flashdata('eliminar', 'Materia eliminada');
        redirect('materia/index');
      }else {
        show_error('No puede eliminar la materia, existen cursos, inscripciones, mesas o correlativas asociadas.');
      }
    }
    else
    show_error('La materia que está intentando eliminar no existe.');
  }

}
