<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Nivel extends CI_Controller{
  //funcion contructor de clase nivel
  function __construct()
  {
    parent::__construct();
    is_logged_in();
    validar_acceso();
    $this->load->model('Nivel_model');
    $this->load->model('Carrera_model');
  }

  /*
  * Listado de niveles
  */
  function index()
  {
    $data['title'] = 'Niveles - ESMN';
    $data['page_title'] = 'Nivel';

    $data['niveles'] = $this->Nivel_model->get_all_niveles();

    //Botones de acciones
    $data['boton_edit']=validar_botones('edit');
    $data['boton_add']=validar_botones('add');
    $data['boton_remove']=validar_botones('remove');

    $this->load->view('templates/header',$data);
    $this->load->view('nivel/index',$data);
    $this->load->view('templates/footer');
  }

  /*
  * Funcion que permite agregar un nuevo nivel al listado
  */
  function add()
  {
    $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]|is_unique[nivel.nombre]');

    if($this->form_validation->run())
    {
      $params = array(
        'nombre' => $this->input->post('nombre'),
      );

      $nivel_id = $this->Nivel_model->add_nivel($params);
      redirect('nivel/index');
    }
    else
    {
      $data['title'] = 'Niveles - ESMN';
      $data['page_title'] = 'Nuevo Nivel';

      $this->load->view('templates/header',$data);
      $this->load->view('nivel/add',$data);
      $this->load->view('templates/footer');
    }
  }

  /*
  * Funcion que permite editar un nivel del listado
  */
  function edit($id)
  {
    // check if the nivel exists before trying to edit it
    $data['nivel'] = $this->Nivel_model->get_nivel($id);

    if(isset($data['nivel']['id']))
    {
      $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]|is_unique[nivel.id]');

      $nivel_exist = $this->Nivel_model->get_nivel_by_nombre($this->input->post('nombre'));
      if($this->form_validation->run() && ($data['nivel']['nombre'] == $this->input->post('nombre') || !isset($nivel_exist['nombre'])))
      {
        $params = array(
          'nombre' => $this->input->post('nombre'),
        );

        $this->Nivel_model->update_nivel($id,$params);
        $this->session->set_flashdata('editar', 'Se guardaron los cambios');
        redirect('nivel/index');
      }
      else
      {
        $data['title'] = 'Niveles - ESMN';
        $data['page_title'] = 'Nivel';

        $this->load->view('templates/header',$data);
        $this->load->view('nivel/edit',$data);
        $this->load->view('templates/footer');
      }
    }
    else
    show_error('EL nivel que intenta editar, no existe.');
  }

  /*
  * Funcion que permite eliminar un nivel que no este asociado a ninguna carrera
  */
  function remove($id)
  {
    $nivel = $this->Nivel_model->get_nivel($id);

    // Se comprueba que el nivel existe antes de intentar eliminarlo
    if(isset($nivel['id']))
    {
      $carreras = $this->Carrera_model->get_all_carreras(array(),array('row'=>'id_nivel','value'=>$id));
      if (empty($carreras)) {
        // $this->Nivel_model->delete_nivel($id);
        $this->Nivel_model->update_nivel($id,array('activo'=>0));
        $this->session->set_flashdata('eliminar', 'Nivel eliminado');
        redirect('nivel/index');
      }else {
        show_error('El nivel no puede ser borrado, ya que esta asociado a una/s carrera/s.');
      }
    }
    else
    show_error('No existe el nivel que quiere eliminar.');
  }

  function getNiveles(){
    if ($this->input->is_ajax_request() && !empty($_POST)) {
      $id_persona=$this->input->post('id_persona');
      $query=$this->Nivel_model->getNiveles($id_persona);
      echo json_encode($query);
    }
    return false;

  }

}
