<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Nivel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Nivel_model');
        $this->load->model('Carrera_model');
    }

    /*
     * Listing of niveles
     */
    function index()
    {
      $data['title'] = 'Niveles - ESMN';
      $data['page_title'] = 'Nivel';
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('nivel/index?');
        $config['total_rows'] = $this->Nivel_model->get_all_niveles_count();
        $this->pagination->initialize($config);

        $data['niveles'] = $this->Nivel_model->get_all_niveles($params);


        $this->load->view('templates/header',$data);
        $this->load->view('nivel/index',$data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new nivel
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');

		if($this->form_validation->run())
        {
            $params = array(
				'nombre' => $this->input->post('nombre'),
            );

            $nivel_id = $this->Nivel_model->add_nivel($params);
            redirect('nivel/index');
        }
        else
        {
          $data['title'] = 'Niveles - ESMN';
          $data['page_title'] = 'Nivel';

            $this->load->view('templates/header',$data);
            $this->load->view('nivel/add',$data);
            $this->load->view('templates/footer');
        }
    }

    /*
     * Editing a nivel
     */
    function edit($id)
    {
        // check if the nivel exists before trying to edit it
        $data['nivel'] = $this->Nivel_model->get_nivel($id);

        if(isset($data['nivel']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');

			if($this->form_validation->run())
            {
                $params = array(
					'nombre' => $this->input->post('nombre'),
                );

                $this->Nivel_model->update_nivel($id,$params);
                redirect('nivel/index');
            }
            else
            {
              $data['title'] = 'Niveles - ESMN';
              $data['page_title'] = 'Nivel';

                $this->load->view('templates/header',$data);
                $this->load->view('nivel/edit',$data);
                $this->load->view('templates/footer');
            }
        }
        else
            show_error('The nivel you are trying to edit does not exist.');
    }

    /*
     * Deleting nivel
     */
    function remove($id)
    {
        $nivel = $this->Nivel_model->get_nivel($id);

        // check if the nivel exists before trying to delete it
        if(isset($nivel['id']))
        {
          $carreras = $this->Carrera_model->get_all_carreras(array(),array('row'=>'id_nivel','value'=>$id));
          if (empty($carreras)) {
            $this->Nivel_model->delete_nivel($id);
            redirect('nivel/index');
          }else {
            show_error('El nivel no puede ser borrado, ya que esta asociado a una/s carrera/s.');
          }
        }
        else
            show_error('No existe el nivel que quiere eliminar.');
    }

}
