<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Perfil_usuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perfil_usuario_model');
    }

    /*
     * Listing of perfil_usuario
     */
    function index()
    {
        $data['perfil_usuario'] = $this->Perfil_usuario_model->get_all_perfil_usuario();

        $data['_view'] = 'perfil_usuario/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perfil_usuario
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'permisos' => $this->input->post('permisos'),
            );

            $perfil_usuario_id = $this->Perfil_usuario_model->add_perfil_usuario($params);
            redirect('perfil_usuario/index');
        }
        else
        {
            $data['_view'] = 'perfil_usuario/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a perfil_usuario
     */
    function edit($id_usuario)
    {
        // check if the perfil_usuario exists before trying to edit it
        $data['perfil_usuario'] = $this->Perfil_usuario_model->get_perfil_usuario($id_usuario);

        if(isset($data['perfil_usuario']['id_usuario']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'permisos' => $this->input->post('permisos'),
                );

                $this->Perfil_usuario_model->update_perfil_usuario($id_usuario,$params);
                redirect('perfil_usuario/index');
            }
            else
            {
                $data['_view'] = 'perfil_usuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perfil_usuario you are trying to edit does not exist.');
    }

    /*
     * Deleting perfil_usuario
     */
    function remove($id_usuario)
    {
        $perfil_usuario = $this->Perfil_usuario_model->get_perfil_usuario($id_usuario);

        // check if the perfil_usuario exists before trying to delete it
        if(isset($perfil_usuario['id_usuario']))
        {
            $this->Perfil_usuario_model->delete_perfil_usuario($id_usuario);
            redirect('perfil_usuario/index');
        }
        else
            show_error('The perfil_usuario you are trying to delete does not exist.');
    }

    public function edit_permission($id){
      $data['perfil'] = $this->Perfil_usuario_model->get_perfil_usuario($id);

      if(isset($data['perfil']['id'])){
        $this->load->helper('file');
        // obtener nombres de controladores
        $controllers = get_filenames( APPPATH . 'controllers/' );
        foreach( $controllers as $k => $v ){
          if( strpos( $v, '.php' ) === FALSE) {
            unset( $controllers[$k] );
          }
        }

        foreach( $controllers as $controller ){
          include_once APPPATH . 'controllers/' . $controller;
          // obtener nombres de metodos y construir un arreglo asociativo
          $methods = get_class_methods( str_replace( '.php', '', $controller ) );

          foreach( $methods as $method ){
            if ($method!='__construct' && $method!='get_instance') {
              $permisos[str_replace('.php', '', $controller)][$method] = 'valor';
            }
          }
        }


        $data['permisos'] = $permisos;
        $data['title'] = 'Editar permisos - CeciliaESMN';
        $data['page_title'] = "Editar permisos de ".$data['perfil']['nombre'];
        // echo '<pre>';
        //         print_r($permisos);
        //         echo  '</pre>';
        $this->load->view('templates/header',$data);
        $this->load->view('perfil/edit_permission',$data);
        $this->load->view('templates/footer',$data);

      }
      else
      show_error('The perfil you are trying to edit does not exist.');

    }

}
