<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Perfil extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perfil_model');
    }

    /*
     * Listing of perfiles
     */
    function index()
    {
        $data['title']='Perfiles - CeciliaESMN';
        $data['page_title']='Perfiles';
        $data['perfiles'] = $this->Perfil_model->get_all_perfiles();

        //$data['_view'] = 'perfil/index';
        $this->load->view('templates/header',$data);
        $this->load->view('perfil/index',$data);
        $this->load->view('templates/footer',$data);
    }

    /*
     * Adding a new perfil
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');

		if($this->form_validation->run())
        {
            $params = array(
				'nombre' => $this->input->post('nombre'),
            );

            $perfil_id = $this->Perfil_model->add_perfil($params);
            redirect('perfil/index');
        }
        else
        {
            $data['title'] = 'Agregar perfil - CeciliaESMN';
            $data['page_title'] = 'Agregar perfil';
            $data['_view'] = 'perfil/add';
            $this->load->view('templates/header',$data);
            $this->load->view('perfil/add',$data);
            $this->load->view('templates/footer',$data);
        }
    }

    /*
     * Editing a perfil
     */
    function edit($id)
    {
        // check if the perfil exists before trying to edit it
        $data['perfil'] = $this->Perfil_model->get_perfil($id);

        if(isset($data['perfil']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');

			if($this->form_validation->run())
            {
                $params = array(
					'nombre' => $this->input->post('nombre'),
                );

                $this->Perfil_model->update_perfil($id,$params);
                redirect('perfil/index');
            }
            else
            {
              $data['title'] = 'Editar perfil - CeciliaESMN';
              $data['page_title'] = 'Editar perfil';
                $data['_view'] = 'perfil/edit';
                $this->load->view('templates/header',$data);
                $this->load->view('perfil/edit',$data);
                $this->load->view('templates/footer',$data);
            }
        }
        else
            show_error('The perfil you are trying to edit does not exist.');
    }

    /*
     * Deleting perfil
     */
    function remove($id)
    {
        //$id = $this->input->get('id');
        $perfil = $this->Perfil_model->get_perfil($id);

        // check if the perfil exists before trying to delete it
        if(isset($perfil['id']))
        {
            $this->Perfil_model->delete_perfil($id);
            redirect('perfil/index');
        }
        else
            show_error('The perfil you are trying to delete does not exist.');
    }

}
