<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perfil_usuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perfil_usuario_model');
    } 

    /*
     * Listing of perfil_usuario
     */
    function index()
    {
        $data['perfil_usuario'] = $this->Perfil_usuario_model->get_all_perfil_usuario();
        
        $data['_view'] = 'perfil_usuario/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perfil_usuario
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'permisos' => $this->input->post('permisos'),
            );
            
            $perfil_usuario_id = $this->Perfil_usuario_model->add_perfil_usuario($params);
            redirect('perfil_usuario/index');
        }
        else
        {            
            $data['_view'] = 'perfil_usuario/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perfil_usuario
     */
    function edit($id_usuario)
    {   
        // check if the perfil_usuario exists before trying to edit it
        $data['perfil_usuario'] = $this->Perfil_usuario_model->get_perfil_usuario($id_usuario);
        
        if(isset($data['perfil_usuario']['id_usuario']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'permisos' => $this->input->post('permisos'),
                );

                $this->Perfil_usuario_model->update_perfil_usuario($id_usuario,$params);            
                redirect('perfil_usuario/index');
            }
            else
            {
                $data['_view'] = 'perfil_usuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perfil_usuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting perfil_usuario
     */
    function remove($id_usuario)
    {
        $perfil_usuario = $this->Perfil_usuario_model->get_perfil_usuario($id_usuario);

        // check if the perfil_usuario exists before trying to delete it
        if(isset($perfil_usuario['id_usuario']))
        {
            $this->Perfil_usuario_model->delete_perfil_usuario($id_usuario);
            redirect('perfil_usuario/index');
        }
        else
            show_error('The perfil_usuario you are trying to delete does not exist.');
    }
    
}
