<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Periodo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        validar_acceso();
        is_logged_in();
        $this->load->model('Periodo_model');
    } 

    /*
     * Listing of periodo
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('periodo/index?');
        $config['total_rows'] = $this->Periodo_model->get_all_periodos_count();
        $this->pagination->initialize($config);
        
        
        
        $data['periodos'] = $this->Periodo_model->get_all_periodo();
        
        $data['title'] = 'Materias - ESMN';
        $data['page_title'] = 'Periodo';
        
        //validar botones
        $data['boton_edit']=validar_botones('edit');
        $data['boton_add']=validar_botones('add');
        $data['boton_remove']=validar_botones('remove');
        
        $this->load->view('templates/header',$data);
        $this->load->view('periodo/index',$data);
        $this->load->view('templates/footer');
    
    }

    /*
     * Adding a new periodo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_tipo_periodo' => $this->input->post('id_tipo_periodo'),
				'desde' => $this->input->post('desde'),
				'hasta' => $this->input->post('hasta'),
            );
            
            $periodo_id = $this->Periodo_model->add_periodo($params);
            redirect('periodo/index');
        }
        else
        {            
            $data['_view'] = 'periodo/add';
            $this->load->view('periodo/index',$data);
        }
    }  

    /*
     * Editing a periodo
     */
    function edit($id)
    {   
        // check if the periodo exists before trying to edit it
        $data['periodo'] = $this->Periodo_model->get_periodo($id);
        
        if(isset($data['periodo']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_tipo_periodo' => $this->input->post('id_tipo_periodo'),
					'desde' => $this->input->post('desde'),
					'hasta' => $this->input->post('hasta'),
                );

                $this->Periodo_model->update_periodo($id,$params);            
                redirect('periodo/index');
            }
            else
            {
                $data['_view'] = 'periodo/edit';
                $this->load->view('periodo/index',$data);
            }
        }
        else
            show_error('The periodo you are trying to edit does not exist.');
    } 

    /*
     * Deleting periodo
     */
    function remove($id)
    {
        $periodo = $this->Periodo_model->get_periodo($id);

        // check if the periodo exists before trying to delete it
        if(isset($periodo['id']))
        {
            $this->Periodo_model->delete_periodo($id);
            redirect('periodo/index');
        }
        else
            show_error('The periodo you are trying to delete does not exist.');
    }
    
}
