<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Provincia extends CI_Controller{
  function __construct()
  {
    parent::__construct();
    $this->load->model('Provincia_model','Provincia',TRUE);
  }

  /*
  * Listing of provincias
  */
  function index()
  {
    $data['page_title'] = 'Provincias - ESMN';
    $params['limit'] = RECORDS_PER_PAGE;
    $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

    $config = $this->config->item('pagination');
    $config['base_url'] = site_url('provincia/index?');
    $config['total_rows'] = $this->Provincia->get_all_provincias_count();
    $this->pagination->initialize($config);

    $data['provincias'] = $this->Provincia->get_all_provincias($params);

    $this->load->view('templates/header',$data);
    $this->load->view('provincia/index',$data);
    $this->load->view('templates/footer');
  }

  /*
  * Adding a new provincia
  */
  function add()
  {
    $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');

    if($this->form_validation->run())
    {
      $params = array(
        'nombre' => $this->input->post('nombre'),
      );

      $provincia_id = $this->Provincia->add_provincia($params);
      redirect('provincia/index');
    }
    else
    {
      $data['title'] = 'Nueva Provincia - ESMN';
      $this->load->view('templates/header',$data);
      $this->load->view('provincia/add');
      $this->load->view('templates/footer');
    }
  }

  /*
  * Editing a provincia
  */
  function edit($id)
  {
    // check if the provincia exists before trying to edit it
    $data['provincia'] = $this->Provincia->get_provincia($id);

    if(isset($data['provincia']['id']))
    {
      $this->load->library('form_validation');

      $this->form_validation->set_rules('nombre','Nombre','required|max_length[64]');

      if($this->form_validation->run())
      {
        $params = array(
          'nombre' => $this->input->post('nombre'),
        );

        $this->Provincia->update_provincia($id,$params);
        redirect('provincia/index');
      }
      else
      {
        $data['_view'] = 'provincia/edit';
        $this->load->view('layouts/main',$data);
      }
    }
    else
    show_error('The provincia you are trying to edit does not exist.');
  }

  /*
  * Deleting provincia
  */
  function remove($id)
  {
    $provincia = $this->Provincia->get_provincia($id);

    // check if the provincia exists before trying to delete it
    if(isset($provincia['id']))
    {
      $this->Provincia->delete_provincia($id);
      redirect('provincia/index');
    }
    else
    show_error('The provincia you are trying to delete does not exist.');
  }

}
