<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_periodo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        validar_acceso();
        is_logged_in();
        $this->load->model('Tipo_periodo_model');
        
    } 

    /*
     * Listing of tipo_periodo
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tipo_periodo/index?');
        $config['total_rows'] = $this->Tipo_periodo_model->get_all_tipo_periodo_count();
        $this->pagination->initialize($config);
        
        $data['tipo_periodos'] = $this->Tipo_periodo_model->get_all_tipo_periodo();
        
        $data['title'] = 'Materias - ESMN';
        $data['page_title'] = 'Tipo de periodo';
        
        //validar botones
        $data['boton_edit']=validar_botones('edit');
        $data['boton_add']=validar_botones('add');
        $data['boton_remove']=validar_botones('remove');
        
        $this->load->view('templates/header',$data);
        $this->load->view('tipo_periodo/index',$data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new tipo_periodo
     */
    function add()
    {   
        $this->form_validation->set_rules('descripcion','Descripcion','required|max_length[128]');
        if($this->form_validation->run())     
        {   
            $params = array(
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $tipo_periodo_id = $this->Tipo_periodo_model->add_tipo_periodo($params);
            $this->session->set_flashdata('crear', 'Nueva materia creada');
            redirect('tipo_periodo/index');
        }
        else
        {            
            $data['title'] = 'Materia - ESMN';
            $data['page_title'] = 'Nuevo Descripcíon de Periodo';
            $data['all_periodos'] = $this->Tipo_periodo_model->get_all_tipo_periodo();
            
            $this->load->view('templates/header',$data);
            $this->load->view('tipo_periodo/add',$data);
            $this->load->view('templates/footer');
        }
    }  

    /*
     * Editing a tipo_periodo
     */
    function edit($id)
    {   
        // check if the tipo_periodo exists before trying to edit it
        $data['tipo_periodo'] = $this->Tipo_periodo_model->get_tipo_periodo($id);
        
        if(isset($data['tipo_periodo']['id']))
        {
            $this->form_validation->set_rules('descripcion','Descripcion','required|max_length[128]');
            if($this->form_validation->run())
            {   
                $params = array('descripcion' => $this->input->post('descripcion'),
            );

                $this->Tipo_periodo_model->update_tipo_periodo($id,$params);
                $this->session->set_flashdata('editar', 'Se guardaron los cambios');
                redirect('tipo_periodo/index');
            }
            else
            {
                $data['title'] = 'Materia - ESMN';
                $data['page_title'] = 'Materia -> '.$data['tipo_periodo']['descripcion'];
                
                $data['all_periodos'] = $this->Tipo_periodo_model->get_all_tipo_periodo();
                $this->load->view('templates/header',$data);
                $this->load->view('tipo_periodo/edit',$data);
                $this->load->view('templates/footer');
            }
        }
        else
            show_error('The tipo_periodo you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_periodo
     */
    function remove($id)
    {
        $tipo_periodo = $this->Tipo_periodo_model->get_tipo_periodo($id);

        // check if the tipo_periodo exists before trying to delete it
        if(isset($tipo_periodo['id']))
        {
            $this->Tipo_periodo_model->delete_tipo_periodo($id);
            redirect('tipo_periodo/index');
        }
        else
            show_error('The tipo_periodo you are trying to delete does not exist.');
    }
    
}
