<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Tipo_periodo extends CI_Controller{
  function __construct()
  {
    parent::__construct();
    validar_acceso();
    is_logged_in();
    $this->load->model('Tipo_periodo_model');

  }

  /*
  * Listing of tipo_periodo
  */
  function index()
  {
    $data['tipo_periodos'] = $this->Tipo_periodo_model->get_all_tipo_periodo();

    $data['title'] = 'Tipos de periodo - ESMN';
    $data['page_title'] = 'Tipos de periodo';

    //validar botones
    $data['boton_edit']=validar_botones('edit');
    $data['boton_add']=validar_botones('add');
    $data['boton_remove']=validar_botones('remove');

    $this->load->view('templates/header',$data);
    $this->load->view('tipo_periodo/index',$data);
    $this->load->view('templates/footer');
  }

  /*
  * Adding a new tipo_periodo
  */
  function add()
  {
    $this->form_validation->set_rules('descripcion','Descripcion','required|max_length[128]|is_unique[tipo_periodo.descripcion]');
    if($this->form_validation->run())
    {
      $params = array(
        'descripcion' => $this->input->post('descripcion',TRUE),
      );

      $tipo_periodo_id = $this->Tipo_periodo_model->add_tipo_periodo($params);
      $this->session->set_flashdata('crear', 'Nueva materia creada');
      redirect('tipo_periodo/index');
    }
    else
    {
      $data['title'] = 'Nuevo tipo de Periodo - ESMN';
      $data['page_title'] = 'Nuevo tipo de Periodo';

      $this->load->view('templates/header',$data);
      $this->load->view('tipo_periodo/add',$data);
      $this->load->view('templates/footer');
    }
  }

  /*
  * Editing a tipo_periodo
  */
  function edit($id)
  {
    // check if the tipo_periodo exists before trying to edit it
    $data['tipo_periodo'] = $this->Tipo_periodo_model->get_tipo_periodo($id);

    if(isset($data['tipo_periodo']['id']))
    {
      if($this->input->post('descripcion') != $data['tipo_periodo']['descripcion']) {
        $is_unique =  '|is_unique[tipo_periodo.descripcion]';
      } else {
        $is_unique =  '';
      }
      
      $this->form_validation->set_rules('descripcion','Descripcion','required|max_length[128]'.$is_unique);
      if($this->form_validation->run())
      {
        $params = array('descripcion' => $this->input->post('descripcion'),
      );

      $this->Tipo_periodo_model->update_tipo_periodo($id,$params);
      $this->session->set_flashdata('editar', 'Se guardaron los cambios');
      redirect('tipo_periodo/index');
    }
    else
    {
      $data['title'] = 'Materia - ESMN';
      $data['page_title'] = 'Tipo de periodo -> '.$data['tipo_periodo']['descripcion'];

      $this->load->view('templates/header',$data);
      $this->load->view('tipo_periodo/edit',$data);
      $this->load->view('templates/footer');
    }
  }
  else
  show_error('The tipo_periodo you are trying to edit does not exist.');
}

/*
* Deleting tipo_periodo
*/
function remove($id)
{
  $tipo_periodo = $this->Tipo_periodo_model->get_tipo_periodo($id);

  // check if the tipo_periodo exists before trying to delete it
  if(isset($tipo_periodo['id']))
  {
    $this->Tipo_periodo_model->delete_tipo_periodo($id);
    redirect('tipo_periodo/index');
  }
  else
  show_error('The tipo_periodo you are trying to delete does not exist.');
}

}
