<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario extends CI_Controller{

    function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
    } 

    /*
     * Listing of usuarios
     */
    function index()
    {
        $data['page_title']='Usuarios';
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('usuario/index?');
        $config['total_rows'] = $this->Usuario_model->get_all_usuarios_count();
        $this->pagination->initialize($config);

        $data['usuarios'] = $this->Usuario_model->get_all_usuarios($params);
        
        $data['_view'] = 'usuario/index';
         $this->load->view('templates/header',$data);
        $this->load->view('usuario/index',$data);
        $this->load->view('templates/footer',$data);
    }

    /*
     * Adding a new usuario
     */
    function add()
    {   
        $data['page_title']= 'Usuario';
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','max_length[256]');
		$this->form_validation->set_rules('id_persona','Id Persona','required|integer');
		$this->form_validation->set_rules('username','Username','max_length[128]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_persona' => $this->input->post('id_persona'),
				'password' => $this->input->post('password'),
				'username' => $this->input->post('username'),
            );
            
            $usuario_id = $this->Usuario_model->add_usuario($params);
            redirect('usuario/index');
        }
        else
        {
			$this->load->model('Persona_model');
			$data['all_personas'] = $this->Persona_model->get_all_personas();
            
            $data['_view'] = 'usuario/add';
            $this->load->view('templates/header',$data);
            $this->load->view('usuario/add',$data);
            $this->load->view('templates/footer',$data);
        }
    }  

    /*
     * Editing a usuario
     */
    function edit($id)
    {   
        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($id);
        
        if(isset($data['usuario']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','max_length[256]');
			$this->form_validation->set_rules('id_persona','Id Persona','required|integer');
			$this->form_validation->set_rules('username','Username','max_length[128]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_persona' => $this->input->post('id_persona'),
					'password' => $this->input->post('password'),
					'username' => $this->input->post('username'),
                );

                $this->Usuario_model->update_usuario($id,$params);            
                redirect('usuario/index');
            }
            else
            {
				$this->load->model('Persona_model');
				$data['all_personas'] = $this->Persona_model->get_all_personas();

                $data['_view'] = 'usuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The usuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting usuario
     */
    function remove($id)
    {
        $usuario = $this->Usuario_model->get_usuario($id);

        // check if the usuario exists before trying to delete it
        if(isset($usuario['id']))
        {
            $this->Usuario_model->delete_usuario($id);
            redirect('usuario/index');
        }
        else
            show_error('The usuario you are trying to delete does not exist.');
    }
    
}
