<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Asistencia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get asistencia by id_asiste
     */
    function get_asistencia($id_curso)
    {
      $this->db->select('asiste.id,asiste.id_estado,asiste.id_persona,
      persona.nombre,persona.apellido,numero_documento,id_materia,id_periodo,materia.nombre AS "materia",
      curso.id AS "id_curso",diascursado,diassemana,curso.activo,tipo_periodo.descripcion AS "periodo",desde,hasta');
      $this->db->from('asiste');
      $this->db->join('persona', 'persona.id = asiste.id_persona','right');
      $this->db->join('curso', 'curso.id = asiste.id_curso','right');
      $this->db->join('materia', 'materia.id = curso.id_materia','right');
      $this->db->join('periodo', 'periodo.id = curso.id_periodo','right');
      $this->db->join('tipo_periodo', 'tipo_periodo.id = periodo.id_tipo_periodo','right');
      $this->db->order_by('persona.nombre', 'desc');
      $this->db->where(array('curso.id' => $id_curso, 'asiste.id IS NOT NULL' => NULL));

      $query = $this->db->get();
      return $query->result_array();
    }

    /*
     * Get all asistenciacias
     */
    function get_all_asistenciacias()
    {
        $this->db->order_by('id_asiste', 'desc');
        return $this->db->get('asistencia')->result_array();
    }

    /*
     * function to add new asistencia
     */
    function add_asistencia($params)
    {
        $this->db->insert('asistencia',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update asistencia
     */
    function update_asistencia($id_asiste,$params)
    {
        $this->db->where('id_asiste',$id_asiste);
        return $this->db->update('asistencia',$params);
    }

    /*
     * function to delete asistencia
     */
    function delete_asistencia($id_asiste)
    {
        return $this->db->delete('asistencia',array('id_asiste'=>$id_asiste));
    }
}
