<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Catedra_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get catedra by id_curso
     */
    function get_catedra($id_curso)
    {
        return $this->db->get_where('catedra',array('id_curso'=>$id_curso))->row_array();
    }

    /*
     * Get all catedras
     */
    function get_all_catedras($where=array())
    {
      $this->db->select('id_curso,id_persona,nombre,apellido');
      $this->db->from('catedra');
      $this->db->join('persona', 'persona.id = catedra.id_persona','inner');
      $this->db->order_by('id_curso', 'desc');

      if(isset($where) && !empty($where))
      {
          $this->db->where($where['row'], $where['value']);
      }
      $query = $this->db->get();
      return $query->result_array();
    }

    /*
     * function to add new catedra
     */
    function add_catedra($params)
    {
        $this->db->insert('catedra',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update catedra
     */
    function update_catedra($id_curso,$id_persona,$params)
    {
        $this->db->where('id_curso',$id_curso);
        $this->db->where('id_persona',$id_persona);
        return $this->db->update('catedra',$params);
    }

    /*
     * function to delete catedra
     */
    function delete_catedra($id_curso)
    {
        return $this->db->delete('catedra',array('id_curso'=>$id_curso));
    }
}
