<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Curso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get curso by id
     */
    function get_curso($id)
    {
        return $this->db->get_where('curso',array('id'=>$id))->row_array();
    }

    /*
     * Get all curso
     */
//     function get_all_curso()
//     {
//         $this->db->order_by('id', 'desc');
//         return $this->db->get('curso')->result_array();
//     }

    function get_all_curso($where = array())
    {
        $this->db->select('curso.id AS "curso_id",id_materia,id_carrera,id_periodo,materia.nombre,
        diascursado,diassemana,curso.activo,tipo_periodo.descripcion AS "periodo",desde,hasta');
        $this->db->from('curso');
        $this->db->join('materia', 'materia.id = curso.id_materia','inner');
        $this->db->join('periodo', 'periodo.id = curso.id_periodo','inner');
        $this->db->join('tipo_periodo', 'tipo_periodo.id = periodo.id_tipo_periodo','inner');
        $this->db->order_by('materia.nombre', 'desc');

        if(isset($where) && !empty($where))
        {
            $this->db->where($where['row'], $where['value']);
        }
        $query = $this->db->get();
        return $query->result_array();
    }

    /*
     * function to add new curso
     */
    function add_curso($params)
    {
        $this->db->insert('curso',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update curso
     */
    function update_curso($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('curso',$params);
    }

    /*
     * function to delete curso
     */
    function delete_curso($id)
    {
        return $this->db->delete('curso',array('id'=>$id));
    }
    
    
    function get_cursos_de_carrera($id_carrera)
    {
        $this->db->select(' curso.id AS curso_id,id_materia, materia.nombre as materia_nombre, materia.id_carrera as id_carrera');
        $this->db->from('curso');
        $this->db->join('materia', 'materia.id = curso.id_materia', 'inner');
        $this->db->where('materia.id_carrera LIKE "'.$id_carrera.'"');
        
        //$this->db->group_by('inscripcion_materia.id ', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $query = $this->db->get();
        return $query->result_array();
    }
}
