<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Documentacion_model extends CI_Model
{
  function __construct()
  {
    parent::__construct();
  }

  /*
  * Get documentacion by id
  */
  function get_documentacion($id)
  {
    return $this->db->get_where('documentacion',array('id'=>$id))->row_array();
  }

  /*
  * Get all documentacion count
  */
  function get_all_documentacion_count()
  {
    $this->db->from('documentacion');
    return $this->db->count_all_results();
  }

  /*
  * Get all documentacion
  */
  function get_all_documentacion($params = array(),$where = array())
  {
    $this->db->select('documentacion.id AS "documentacion_id",persona.id AS "id_persona",
                      nombre,apellido,numero_documento,genero,fotocopia_dni,titulo_primario,
                      titulo_secundario,otros_titulos,fecha_inscripcion,foto_carnet,certificado_nacimiento,
                      beca,certificado_jucaid,medicacion,enfermedad,trabajo');
    $this->db->from('documentacion');
    $this->db->join('persona', 'persona.id = documentacion.id_persona', 'right');
    $this->db->order_by('documentacion_id', 'desc');
    if(isset($params) && !empty($params))
    {
      $this->db->limit($params['limit'], $params['offset']);
    }
    if(isset($where) && !empty($where))
    {
      $this->db->where($where['row'], $where['value']);
    }
    // return $this->db->get('documentacion')->result_array();
    $query = $this->db->get();
    // var_dump($this->db->last_query());exit;
    return $query->result_array();
  }

  /*
  * function to add new documentacion
  */
  function add_documentacion($params)
  {
    $this->db->insert('documentacion',$params);
    return $this->db->insert_id();
  }

  /*
  * function to update documentacion
  */
  function update_documentacion($id,$params)
  {
    $this->db->where('id',$id);
    return $this->db->update('documentacion',$params);
  }

  /*
  * function to delete documentacion
  */
  function delete_documentacion($id)
  {
    return $this->db->delete('documentacion',array('id'=>$id));
  }
}
