<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class estado_cursado_model extends CI_Model
{
  function __construct()
  {
    parent::__construct();
  }

  /*
  * Get estado_cursado by id
  */
  function get_estado_cursado($id)
  {
    return $this->db->get_where('estado_cursado',array('id'=>$id))->row_array();
  }

  /*
  * Get all estado_cursado count
  */
  function get_all_estado_cursado_count()
  {
    $this->db->from('estado_cursado');
    return $this->db->count_all_results();
  }

  /*
  * Get all estado_cursado
  */
  function get_all_estado_cursado($params = array())
  {
    $this->db->order_by('id', 'desc');
    if(isset($params) && !empty($params))
    {
      $this->db->limit($params['limit'], $params['offset']);
    }
    return $this->db->get('estado_cursado')->result_array();
  }

  /*
  * function to add new estado_cursado
  */
  function add_estado_cursado($params)
  {
    $this->db->insert('estado_cursado',$params);
    return $this->db->insert_id();
  }

  /*
  * function to update estado_cursado
  */
  function update_estado_cursado($id,$params)
  {
    $this->db->where('id',$id);
    return $this->db->update('estado_cursado',$params);
  }

  /*
  * function to delete estado_cursado
  */
  function delete_estado_cursado($id)
  {
    return $this->db->delete('estado_cursado',array('id'=>$id));
  }
}
