<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Estado_asistencia_model extends CI_Model
{
  function __construct()
  {
    parent::__construct();
  }

  /*
  * Get estado_asistencia by id
  */
  function get_estado_asistencia($id)
  {
    return $this->db->get_where('estado_asistencia',array('id'=>$id))->row_array();
  }

  /*
  * Get all estado_asistencia count
  */
  function get_all_estado_asistencia_count()
  {
    $this->db->from('estado_asistencia');
    return $this->db->count_all_results();
  }

  /*
  * Get all estado_asistencia
  */
  function get_all_estado_asistencia($params = array())
  {
    $this->db->order_by('id', 'desc');
    if(isset($params) && !empty($params))
    {
      $this->db->limit($params['limit'], $params['offset']);
    }
    return $this->db->get('estado_asistencia')->result_array();
  }

  /*
  * function to add new estado_asistencia
  */
  function add_estado_asistencia($params)
  {
    $this->db->insert('estado_asistencia',$params);
    return $this->db->insert_id();
  }

  /*
  * function to update estado_asistencia
  */
  function update_estado_asistencia($id,$params)
  {
    $this->db->where('id',$id);
    return $this->db->update('estado_asistencia',$params);
  }

  /*
  * function to delete estado_asistencia
  */
  function delete_estado_asistencia($id)
  {
    return $this->db->delete('estado_asistencia',array('id'=>$id));
  }
}
