<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Estado_inscripcion_final_model extends CI_Model
{
  function __construct()
  {
    parent::__construct();
  }

  /*
  * Get estado_inscripcion_final by id
  */
  function get_estado_inscripcion_final($id)
  {
    return $this->db->get_where('estado_inscripcion_final',array('id'=>$id))->row_array();
  }

  /*
  * Get all estado_inscripcion_final count
  */
  function get_all_estado_inscripcion_final_count()
  {
    $this->db->from('estado_inscripcion_final');
    return $this->db->count_all_results();
  }

  /*
  * Get all estado_inscripcion_final
  */
  function get_all_estado_inscripcion_final($params = array())
  {
    $this->db->order_by('id', 'desc');
    if(isset($params) && !empty($params))
    {
      $this->db->limit($params['limit'], $params['offset']);
    }
    return $this->db->get('estado_inscripcion_final')->result_array();
  }

  /*
  * function to add new estado_inscripcion_final
  */
  function add_estado_inscripcion_final($params)
  {
    $this->db->insert('estado_inscripcion_final',$params);
    return $this->db->insert_id();
  }

  /*
  * function to update estado_inscripcion_final
  */
  function update_estado_inscripcion_final($id,$params)
  {
    $this->db->where('id',$id);
    return $this->db->update('estado_inscripcion_final',$params);
  }

  /*
  * function to delete estado_inscripcion_final
  */
  function delete_estado_inscripcion_final($id)
  {
    return $this->db->delete('estado_inscripcion_final',array('id'=>$id));
  }
}
