<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Inscripcion_materia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get inscripcion_materia by id
     */
    function get_inscripcion_materia($id)
    {
        return $this->db->get_where('inscripcion_materia',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all inscripcion_materia
     */
    function get_all_inscripcion_materia()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('inscripcion_materia')->result_array();
    }
        
    /*
     * function to add new inscripcion_materia
     */
    function add_inscripcion_materia($params)
    {
        $this->db->insert('inscripcion_materia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update inscripcion_materia
     */
    function update_inscripcion_materia($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('inscripcion_materia',$params);
    }
    
    /*
     * function to delete inscripcion_materia
     */
    function delete_inscripcion_materia($id)
    {
        return $this->db->delete('inscripcion_materia',array('id'=>$id));
    }
}