<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Inscripcion_materia_model extends CI_Model
{
  function __construct()
  {
    parent::__construct();
  }

  /*
  * Get inscripcion_materia by id
  */
  function get_inscripcion_materia($id)
  {
    return $this->db->get_where('inscripcion_materia',array('id'=>$id))->row_array();
  }

  /*
  * Get all inscripcion_materia
  */
  function get_all_inscripcion_materia($where = array())
  {
    $this->db->order_by('id', 'desc');
    if(isset($where) && !empty($where))
    {
      $this->db->where($where['row'], $where['value']);
    }
    return $this->db->get('inscripcion_materia')->result_array();
  }

  function get_all_inscripcion_materia_cursado($id_alumno=null)
  {
    $this->db->select('inscripcion_materia.id AS "id_inscripcion_materia",inscripcion_materia.fecha,
    inscripcion_materia.id_persona, inscripcion_materia.id_curso, id_carrera, tipo_catedra,
    inscripcion_materia.id_materia, estado_inscripcion_inicial.nombre as nombre_estado_inicial,
    id_estado_final, calificacion, materia.nombre AS "nombre_materia",
    persona.nombre AS "nombre_persona", persona.apellido AS "apellido_persona",
    persona.numero_documento AS "numero_documento",estado_inscripcion_final.id as id_estado_final,
    estado_inscripcion_final.nombre as nombre_estado_final,
    porcentaje,faltas');
    $this->db->from('inscripcion_materia');
    $this->db->join('curso', 'inscripcion_materia.id_curso = curso.id', 'left');
    $this->db->join('materia ', 'inscripcion_materia.id_materia  = materia.id', 'left');
    $this->db->join('persona ', 'inscripcion_materia.id_persona  = persona.id', 'left');
    $this->db->join('asiste', 'asiste.id_persona = persona.id and asiste.id_curso = curso.id', 'left');
    $this->db->join('estado_inscripcion_inicial ', 'inscripcion_materia.id_estado_inicial  = estado_inscripcion_inicial.id', 'left');
    $this->db->join('estado_inscripcion_final ', 'inscripcion_materia.id_estado_final  = estado_inscripcion_final.id', 'left');

    if($id_alumno!=null)
    {
        $this->db->where('(inscripcion_materia.id_curso IS NOT NULL OR id_estado_final=5) AND inscripcion_materia.id_persona='.$id_alumno);
    }
    else
    {
        $this->db->where('inscripcion_materia.id_curso IS NOT NULL OR id_estado_final=5');
    }
//     if(isset($where) && !empty($where))
//     {
//       foreach ($where as $w) {
//         $this->db->where($w['row'], $w['value']);
//       }
//     }

    $query = $this->db->get();
    return $query->result_array();
  }

  function get_all_inscripcion_materia_mesa($id_alumno=null)
  {
    $this->db->select('inscripcion_materia.id as id_inscripcion_materia,id_persona,id_curso,id_carrera,
    inscripcion_materia.id_materia, id_mesa,id_estado_inicial, id_estado_final, calificacion,
    mesa.fecha as fecha_mesa,materia.nombre as nombre_materia, persona.nombre as nombre_persona,
    persona.apellido as apellido_persona,persona.numero_documento,estado_inscripcion_inicial.nombre
    as estado_inicial,estado_inscripcion_final.nombre as estado_final');
    $this->db->from('inscripcion_materia');
    $this->db->join('mesa', 'inscripcion_materia.id_mesa = mesa.id', 'left');
    $this->db->join('materia ', 'inscripcion_materia.id_materia  = materia.id', 'left');
    $this->db->join('persona ', 'inscripcion_materia.id_persona  = persona.id', 'left');
    $this->db->join('estado_inscripcion_inicial ', 'inscripcion_materia.id_estado_inicial  = estado_inscripcion_inicial.id', 'left');
    $this->db->join('estado_inscripcion_final ', 'inscripcion_materia.id_estado_final  = estado_inscripcion_final.id', 'left');
    if($id_alumno!=null)
    {
        $this->db->where('(inscripcion_materia.id_mesa IS NOT NULL) AND id_persona='.$id_alumno);
    }
    else
    {
        $this->db->where('inscripcion_materia.id_mesa IS NOT NULL');
    }

    $query = $this->db->get();
    return $query->result_array();
  }

  // funcion comprobar si una persona ya esta registrada en un curso
  public function check_inscripcion($id_persona,$id_curso){
    return $this->db->get_where('inscripcion_materia',array('id_persona'=>$id_persona,'id_curso'=>$id_curso))->row_array();
  }

  // comprobar estado de aprobacion de una materia equivalente sea distinto de 1(desaprobado) o 4(libre)
  public function check_estado($id_persona,$id_materia){
    $this->db->where(array('id_persona'=>$id_persona,'id_materia'=>$id_materia));
    $this->db->where_not_in('inscripcion_materia.id_estado_final',array(1,4));
    return $this->db->get('inscripcion_materia')->row_array();
  }

  public function get_inscripcion_mesa($id,$id_materia,$estado = false,$fecha = false)
  {
      $this->db->select('persona.id AS persona_id,persona.nombre,apellido,numero_documento,
                        tipo_documento.nombre as tipo_documento,inscripcion_materia.id,
                        materia.nombre as materia,materia.id_carrera as id_carrera,inscripcion_materia.calificacion,
                        estado_inscripcion_inicial.nombre as estado_inicial,estado_inscripcion_final.nombre as estado_final,
                        inscripcion_materia.fecha,nivel.nombre as nivel, carrera.nombre as carrera');
      $this->db->from('inscripcion_materia');
      $this->db->join('persona', 'inscripcion_materia.id_persona=persona.id', 'inner');
      $this->db->join('mesa', 'mesa.id=inscripcion_materia.id_mesa', 'inner');
      $this->db->join('materia', 'materia.id = mesa.id_materia', 'inner');
      $this->db->join('carrera', 'carrera.id = materia.id_carrera', 'inner');
      $this->db->join('nivel', 'nivel.id = carrera.id_nivel', 'inner');
      $this->db->join('tipo_documento', 'persona.id_tipo_documento = tipo_documento.id', 'inner');
      $this->db->join('estado_inscripcion_inicial', 'estado_inscripcion_inicial.id = inscripcion_materia.id_estado_inicial', 'left');
      $this->db->join('estado_inscripcion_final', 'estado_inscripcion_final.id = inscripcion_materia.id_estado_final', 'left');

      $this->db->where('persona.id='.$id.' AND materia.id="'.$id_materia.'"');
      if ($estado) {
        $this->db->where('inscripcion_materia.id_estado_final IS NOT null');
      }
      if ($fecha) {
        $this->db->where('inscripcion_materia.fecha="'.$fecha.'"');
      }

      $query = $this->db->get();
      return $query->result_array();
  }

  /*
  * function to add new inscripcion_materia
  */
  function add_inscripcion_materia($params)
  {
    $this->db->insert('inscripcion_materia',$params);
    return $this->db->insert_id();
  }

  /*
  * function to update inscripcion_materia
  */
  function update_inscripcion_materia($id,$params)
  {
    $this->db->where('id',$id);
    return $this->db->update('inscripcion_materia',$params);
  }

  /*
  * function to delete inscripcion_materia
  */
  function delete_inscripcion_materia($id)
  {
    return $this->db->delete('inscripcion_materia',array('id'=>$id));
  }
}
