<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Materia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get materia by id
     */
    function get_materia($id)
    {
        return $this->db->get_where('materia',array('id'=>$id))->row_array();
    }

    /*
     * Get all materias count
     */
    function get_all_materias_count()
    {
        $this->db->from('materia');
        return $this->db->count_all_results();
    }

    /*
     * Get all materias
     */
    function get_all_materias($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('materia')->result_array();
    }

    /*
     * function to add new materia
     */
    function add_materia($params)
    {
        $this->db->insert('materia',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update materia
     */
    function update_materia($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('materia',$params);
    }

    /*
     * function to delete materia
     */
    function delete_materia($id)
    {
        return $this->db->delete('materia',array('id'=>$id));
    }
}
