<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Mensaje_model extends CI_Model
{
  //constructor de modelo nivel
  function __construct()
  {
    parent::__construct();
  }

  function get_all()
  {
    return $this->db->get('mensaje')->result_array();
  }

  public function get_chat_contact($id_usuario_actual){
    //     SELECT id_chat,id_usuario_remitente,id_usuario_destino,fecha,visto,texto, p1.nombre "nombre_remitente", p1.apellido "apellido_remitente",
    // p2.nombre "nombre_destino", p2.apellido "apellido_destino"
    // from mensaje
    // join usuario u1 on u1.id=mensaje.id_usuario_remitente
    // join persona p1 on p1.id=u1.id_persona
    // join usuario u2 on u2.id=mensaje.id_usuario_destino
    // join persona p2 on p2.id=u2.id_persona
    // WHERE (id_chat LIKE '6_%' OR id_chat LIKE '%6')
    // and mensaje.id in (select max(id) from mensaje
    // GROUP by id_chat)
    $query = $this->db->query("SELECT id_chat,id_usuario_remitente,id_usuario_destino,fecha,visto,texto,
      p1.nombre 'nombre_remitente', p1.apellido 'apellido_remitente', p1.foto 'foto_remitente',
      p2.nombre 'nombre_destino', p2.apellido 'apellido_destino', p2.foto 'foto_destino'
      FROM mensaje
      JOIN usuario u1 ON u1.id=mensaje.id_usuario_remitente
      JOIN persona p1 ON p1.id=u1.id_persona
      JOIN usuario u2 ON u2.id=mensaje.id_usuario_destino
      JOIN persona p2 ON p2.id=u2.id_persona
      WHERE (id_chat LIKE '".$id_usuario_actual."_%' OR id_chat LIKE '%$id_usuario_actual')
      AND mensaje.id IN (SELECT MAX(id) FROM mensaje
      GROUP BY id_chat)");
      return $query->result_array();
      // $this->db->select(['id_chat','id_usuario_destino','nombre', 'apellido', 'foto'])
      // ->from('mensaje')
      // ->join('usuario','usuario.id=mensaje.id_usuario_destino','inner')
      // ->join('persona','usuario.id_persona=persona.id','inner')
      // ->where("(id_chat LIKE '".$id_usuario_actual."_%' OR id_chat LIKE '%$id_usuario_actual')
      // AND id_usuario_destino != $id_usuario_actual")
      // ->group_by('id_chat');
      // $query = $this->db->get();
      // // print_r($this->db->last_query());
      // return $query->result_array();
    }

    public function get_mensajes_chat($id_chat){ //trae todos los mensajes de una conversacion
      // $this->db->select(['mensaje.*',
      // 'p1.nombre as remitente_nombre', 'p1.apellido as remitente_apellido', 'p1.foto as remitente_foto',
      // 'p2.nombre as destinatario_nombre', 'p2.apellido as destinatario_apellido', 'p2.foto as destinatario_foto'])
      // ->from('mensaje')
      // ->join('usuario u1','mensaje.id_usuario_remitente=u1.id', 'left')
      // ->join('persona p1','p1.id=u1.id_persona')
      // ->join('usuario u2','mensaje.id_usuario_destino=u2.id', 'left')
      // ->join('persona p2','p2.id=u2.id_persona')
      // ->where("id_chat='$id_chat'")
      // ->order_by('fecha desc')
      // ->limit(20);
      // $query = $this->db->get()->order_by('fecha asc');
      // print_r($this->db->last_query());
      // return $query->result_array();
      $query = $this->db->query("(SELECT
      mensaje.*, p1.nombre AS remitente_nombre, p1.apellido AS remitente_apellido, p1.foto AS remitente_foto,
      p2.nombre AS destinatario_nombre, p2.apellido AS destinatario_apellido, p2.foto AS destinatario_foto
      FROM mensaje
      LEFT JOIN usuario u1 ON mensaje.id_usuario_remitente = u1.id
      JOIN persona p1 ON p1.id = u1.id_persona
      LEFT JOIN usuario u2 ON mensaje.id_usuario_destino = u2.id
      JOIN persona p2 ON p2.id = u2.id_persona
      WHERE id_chat = '$id_chat'
      ORDER BY fecha DESC
      LIMIT 20)
      order by fecha ASC");
      return $query->result_array();
    }

    function send($params){
      $this->db->set('fecha', 'NOW()', FALSE);
      $this->db->insert('mensaje',$params);
      return $this->db->insert_id();
    }

  }
