<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Mesa_model extends CI_Model
{
  function __construct()
  {
    parent::__construct();
  }

  /*
  * Get mesa by id
  */
  function get_mesa($id)
  {
    return $this->db->get_where('mesa',array('id'=>$id))->row_array();
  }

  /*
  * Get all mesas
  */
  function get_all_mesas($where = array())
  {
    $this->db->select('mesa.id AS "id_mesa",id_materia,materia.nombre AS "materia",
    id_carrera,fecha');
    $this->db->from('mesa');
    $this->db->join('materia', 'materia.id = mesa.id_materia', 'inner');
    $this->db->order_by('fecha', 'desc');
    if(isset($where) && !empty($where))
    {
      $this->db->where($where['row'], $where['value']);
    }
    $query = $this->db->get();
    return $query->result_array();
  }

  /*
  * function to add new mesa
  */
  function add_mesa($params)
  {
    $this->db->insert('mesa',$params);
    return $this->db->insert_id();
  }

  /*
  * function to update mesa
  */
  function update_mesa($id,$params)
  {
    $this->db->where('id',$id);
    return $this->db->update('mesa',$params);
  }

  /*
  * function to delete mesa
  */
  function delete_mesa($id)
  {
    return $this->db->delete('mesa',array('id'=>$id));
  }
}
