<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Message_model extends CI_Model
{
  //constructor de modelo nivel
  function __construct()
  {
    parent::__construct();
  }

  function get_all()
  {
    return $this->db->get('message')->result_array();
  }
  function add_message($params)
  {
    $this->db->insert('message',$params);
    return $this->db->insert_id();
  }

}
