<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Nivel_model extends CI_Model
{
  //constructor de modelo nivel
    function __construct()
    {
        parent::__construct();
    }

    /*
     * obtinen el nivel a partir del id
     */
    function get_nivel($id)
    {
        return $this->db->get_where('nivel',array('id'=>$id))->row_array();
    }

    function get_nivel_by_nombre($nombre)
    {
        return $this->db->get_where('nivel',array('nombre'=>$nombre))->row_array();
    }
    /*
     * obtiene todos los niveles y los cuenta
     */
    function get_all_niveles_count()
    {
        $this->db->from('nivel');
        return $this->db->count_all_results();
    }

    /*
     * obtiene todos los niveles
     */
    function get_all_niveles($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('nivel')->result_array();
    }

    /*
     * funcion para agregar un nuevo nivel
     */
    function add_nivel($params)
    {
        $this->db->insert('nivel',$params);
        return $this->db->insert_id();
    }

    /*
     * funcion para actualizar un nivel
     */
    function update_nivel($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('nivel',$params);
    }

    /*
     * funcion para eliminar un nivel a partir de su id
     */
    function delete_nivel($id)
    {
        return $this->db->delete('nivel',array('id'=>$id));
    }
}
