<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Nivel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get nivel by id
     */
    function get_nivel($id)
    {
        return $this->db->get_where('nivel',array('id'=>$id))->row_array();
    }

    /*
     * Get all niveles count
     */
    function get_all_niveles_count()
    {
        $this->db->from('nivel');
        return $this->db->count_all_results();
    }

    /*
     * Get all niveles
     */
    function get_all_niveles($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('nivel')->result_array();
    }

    /*
     * function to add new nivel
     */
    function add_nivel($params)
    {
        $this->db->insert('nivel',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update nivel
     */
    function update_nivel($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('nivel',$params);
    }

    /*
     * function to delete nivel
     */
    function delete_nivel($id)
    {
        return $this->db->delete('nivel',array('id'=>$id));
    }
}
