<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perfil_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perfil by id
     */
    function get_perfil($id)
    {
        return $this->db->get_where('perfil',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all perfiles
     */
    function get_all_perfiles()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('perfil')->result_array();
    }
        
    /*
     * function to add new perfil
     */
    function add_perfil($params)
    {
        $this->db->insert('perfil',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perfil
     */
    function update_perfil($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('perfil',$params);
    }
    
    /*
     * function to delete perfil
     */
    function delete_perfil($id)
    {
        return $this->db->delete('perfil',array('id'=>$id));
    }
}
