<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perfil_usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perfil_usuario by id_usuario
     */
    function get_perfil_usuario($id_usuario)
    {
        return $this->db->get_where('perfil_usuario',array('id_usuario'=>$id_usuario))->row_array();
    }
        
    /*
     * Get all perfil_usuario
     */
    function get_all_perfil_usuario()
    {
        $this->db->order_by('id_usuario', 'desc');
        return $this->db->get('perfil_usuario')->result_array();
    }
        
    /*
     * function to add new perfil_usuario
     */
    function add_perfil_usuario($params)
    {
        $this->db->insert('perfil_usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perfil_usuario
     */
    function update_perfil_usuario($id_usuario,$params)
    {
        $this->db->where('id_usuario',$id_usuario);
        return $this->db->update('perfil_usuario',$params);
    }
    
    /*
     * function to delete perfil_usuario
     */
    function delete_perfil_usuario($id_usuario)
    {
        return $this->db->delete('perfil_usuario',array('id_usuario'=>$id_usuario));
    }
}
