<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Persona_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get persona by id
     */
    function get_persona($id)
    {
        return $this->db->get_where('persona',array('id'=>$id))->row_array();
    }

    /*
     * Get all personas count
     */
    function get_all_personas_count()
    {
        $this->db->from('persona');
        return $this->db->count_all_results();
    }

    /*
     * Get all personas
     */
    function get_all_personas($params = array())
    {
      $this->db->select('persona.id AS "persona_id",tipo_documento.nombre AS "tipo_documento",ciudad.nombre AS "ciudad",numero_documento,persona.nombre,apellido,domicilio,telefono,email,fecha_nacimiento');
      $this->db->from('persona');
      $this->db->join('tipo_documento', 'tipo_documento.id = persona.id_tipo_documento', 'join');
      $this->db->join('ciudad', 'ciudad.id = persona.id_ciudad', 'join');
      $this->db->order_by('persona_id', 'desc');
      if(isset($params) && !empty($params))
      {
        $this->db->limit($params['limit'], $params['offset']);
      }
      $query = $this->db->get();
      return $query->result_array();
        // return $this->db->get('persona')->result_array();
    }

    /*
     * function to add new persona
     */
    function add_persona($params)
    {
        $this->db->insert('persona',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update persona
     */
    function update_persona($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('persona',$params);
    }

    /*
     * function to delete persona
     */
    function delete_persona($id)
    {
        return $this->db->delete('persona',array('id'=>$id));
    }
}
