<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Provincia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get provincia by id
     */
    function get_provincia($id)
    {
        return $this->db->get_where('provincia',array('id'=>$id))->row_array();
    }

    /*
     * Get all provincias count
     */
    function get_all_provincias_count()
    {
        $this->db->from('provincia');
        return $this->db->count_all_results();
    }

    /*
     * Get all provincias
     */
    function get_all_provincias($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('provincia')->result_array();
    }

    /*
     * function to add new provincia
     */
    function add_provincia($params)
    {
        $this->db->insert('provincia',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update provincia
     */
    function update_provincia($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('provincia',$params);
    }

    /*
     * function to delete provincia
     */
    function delete_provincia($id)
    {
        return $this->db->delete('provincia',array('id'=>$id));
    }
}
