<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_periodo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_periodo by id
     */
    function get_tipo_periodo($id)
    {
        return $this->db->get_where('tipo_periodo',array('id'=>$id))->row_array();
    }
    
    function get_all_tipo_periodo_count()
    {
        $this->db->from('tipo_periodo');
        return $this->db->count_all_results();
    }
    
    /*
     * Get all tipo_periodo
     */
    function get_all_tipo_periodo()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tipo_periodo')->result_array();
    }
        
    /*
     * function to add new tipo_periodo
     */
    function add_tipo_periodo($params)
    {
        $this->db->insert('tipo_periodo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_periodo
     */
    function update_tipo_periodo($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tipo_periodo',$params);
    }
    
    /*
     * function to delete tipo_periodo
     */
    function delete_tipo_periodo($id)
    {
        return $this->db->delete('tipo_periodo',array('id'=>$id));
    }
}
