<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_documento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_documento by id
     */
    function get_tipo_documento($id)
    {
        return $this->db->get_where('tipo_documento',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tipo_documento
     */
    function get_all_tipo_documento()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tipo_documento')->result_array();
    }
        
    /*
     * function to add new tipo_documento
     */
    function add_tipo_documento($params)
    {
        $this->db->insert('tipo_documento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_documento
     */
    function update_tipo_documento($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tipo_documento',$params);
    }
    
    /*
     * function to delete tipo_documento
     */
    function delete_tipo_documento($id)
    {
        return $this->db->delete('tipo_documento',array('id'=>$id));
    }
}
