<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tutor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tutor by id
     */
    function get_tutor($id)
    {
        return $this->db->get_where('tutor',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tutores count
     */
    function get_all_tutores_count()
    {
        $this->db->from('tutor');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tutores
     */
    function get_all_tutores($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tutor')->result_array();
    }
        
    /*
     * function to add new tutor
     */
    function add_tutor($params)
    {
        $this->db->insert('tutor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tutor
     */
    function update_tutor($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tutor',$params);
    }
    
    /*
     * function to delete tutor
     */
    function delete_tutor($id)
    {
        return $this->db->delete('tutor',array('id'=>$id));
    }
}
