<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Usuario_model extends CI_Model
{
  function __construct()
  {
    parent::__construct();
  }

  /*
  * Get usuario by id
  */
  function get_usuario($id)
  {
    return $this->db->get_where('usuario',array('id'=>$id))->row_array();
  }

  /*
  * Get all usuarios count
  */
  function get_all_usuarios_count()
  {
    $this->db->from('usuario');
    return $this->db->count_all_results();
  }

  /*
  * Get all usuarios
  */
  function get_all_usuarios($params = array())
  {
    $this->db->order_by('id', 'desc');
    if(isset($params) && !empty($params))
    {
      $this->db->limit($params['limit'], $params['offset']);
    }
    return $this->db->get('usuario')->result_array();
  }

  /*
  * function to add new usuario
  */
  function add_usuario($params)
  {
    $this->db->insert('usuario',$params);
    return $this->db->insert_id();
  }

  /*
  * function to update usuario
  */
  function update_usuario($id,$params)
  {
    $this->db->where('id',$id);
    return $this->db->update('usuario',$params);
  }

  /*
  * function to delete usuario
  */
  function delete_usuario($id)
  {
    return $this->db->delete('usuario',array('id'=>$id));
  }

  // funcion comprobar usuario y contraseña
  public function login($username,$password){
    $this->db->select('persona.id AS "persona_id",tipo_documento.nombre AS "tipo_documento",numero_documento,persona.nombre,apellido,usuario.id AS "usuario_id",email,username,id_perfil,permisos');
    $this->db->from('persona');
    $this->db->join('tipo_documento','tipo_documento.id=persona.id_tipo_documento','inner');
    $this->db->join('usuario','usuario.id_persona=persona.id','inner');
    $this->db->join('perfil_usuario','perfil_usuario.id_usuario=usuario.id','inner');
    $this->db->where('username',$username);
    $this->db->where('password',$password);
    $query = $this->db->get();
    if($query->num_rows() == 1){
      return $query->row();
    }else{
      $this->session->set_flashdata('usuario_incorrecto','Los datos introducidos son incorrectos');
      redirect(base_url().'login','refresh');
    }
  }

}
