<?php
/*
* Generated by CRUDigniter v3.2
* www.crudigniter.com
*/

class Usuario_model extends CI_Model
{
  function __construct()
  {
    parent::__construct();
  }


  /*
  * Get usuario by id_persona
  */
  function get_usuario_by_persona($id_persona)
  {
    return $this->db->get_where('usuario',array('id_persona'=>$id_persona))->row_array();
  }

  /*
  * Get usuario by id
  */
  function get_usuario($id)
  {
    // return $this->db->get_where('usuario',array('id'=>$id))->row_array();
    $this->db->select('persona.id AS "persona_id",persona.nombre,apellido,usuario.id AS "usuario_id",
                      username,');
    $this->db->from('usuario');
    $this->db->join('persona', 'persona.id = usuario.id_persona', 'inner');
    $this->db->where('usuario.id',$id);
    $query = $this->db->get();
    return $query->row_array();
  }

  /*
  * Get all usuarios count
  */
  function get_all_usuarios_count()
  {
    $this->db->from('usuario');
    return $this->db->count_all_results();
  }

  /*
  * Get all usuarios
  */
  function get_all_usuarios($params = array())
  {
    $this->db->select('persona.id AS "persona_id",tipo_documento.nombre AS "tipo_documento",
                      numero_documento,persona.nombre,apellido,usuario.id AS "usuario_id",
                      username,id_perfil,perfil.permisos,perfil.nombre AS "rol"');
    $this->db->from('usuario');
    $this->db->join('persona', 'persona.id = usuario.id_persona', 'inner');
    $this->db->join('tipo_documento', 'tipo_documento.id = persona.id_tipo_documento', 'inner');
    $this->db->join('perfil_usuario', 'usuario.id = perfil_usuario.id_usuario', 'inner');
    $this->db->join('perfil', 'perfil.id = perfil_usuario.id_perfil', 'inner');

    $this->db->order_by('usuario_id', 'desc');
    if(isset($params) && !empty($params))
    {
      $this->db->limit($params['limit'], $params['offset']);
    }
    $query = $this->db->get();
    return $query->result_array();
  }

  /*
  * function to add new usuario
  */
  function add_usuario($params)
  {
    $this->db->insert('usuario',$params);
    return $this->db->insert_id();
  }

  /*
  * function to update usuario
  */
  function update_usuario($id,$params)
  {
    $this->db->where('id',$id);
    return $this->db->update('usuario',$params);
  }

  /*
  * function to delete usuario
  */
  function delete_usuario($id)
  {
    return $this->db->delete('usuario',array('id'=>$id));
  }

  // funcion comprobar usuario y contraseña
public function check_password($id,$password){
  return $this->db->get_where('usuario',array('id'=>$id,'password'=>$password))->row_array();
}

  // obtener todos los datos para un logueo exitoso
  public function login($username,$password){
    $this->db->select('persona.id AS "persona_id",tipo_documento.nombre AS "tipo_documento",
                       numero_documento,persona.nombre,apellido,usuario.id AS "usuario_id",
                       email,username,id_perfil,perfil.nombre AS "nombre_perfil",perfil.permisos');
    $this->db->from('persona');
    $this->db->join('tipo_documento','tipo_documento.id=persona.id_tipo_documento','inner');
    $this->db->join('usuario','usuario.id_persona=persona.id','inner');
    $this->db->join('perfil_usuario','perfil_usuario.id_usuario=usuario.id','inner');
    $this->db->join('perfil','perfil.id=perfil_usuario.id_perfil','inner');
    $this->db->where('username',$username);
    $this->db->where('password',$password);
    $query = $this->db->get();
    if($query->num_rows() == 1){
      return $query->row();
    }else{
      $this->session->set_flashdata('usuario_incorrecto','Los datos introducidos son incorrectos');
      redirect(base_url().'login','refresh');
    }
  }

}
